spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_local
    username: local_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true

server:
  port: 8082

logging:
  level:
    root: DEBUG