--liquibase formatted sql
--changeset Joe Biden:002-create-user-statuses
CREATE TABLE IF NOT EXISTS user_statuses (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_status_translations (
                                                        status_id BIGINT NOT NULL REFERENCES user_statuses(id) ON DELETE CASCADE,
                                                        language_code CHAR(2) NOT NULL,
                                                        description VARCHAR(255),
                                                        PRIMARY KEY (status_id, language_code)
);

INSERT INTO user_statuses (code) VALUES ('ACTIVE');