--liquibase formatted sql
--changeset Joe Biden:003-create-genders
CREATE TABLE IF NOT EXISTS genders (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS gender_translations (
                                                   gender_id BIGINT NOT NULL REFERENCES genders(id) ON DELETE CASCADE,
                                                   language_code CHAR(2) NOT NULL,
                                                   description VARCHAR(255),
                                                   PRIMARY KEY (gender_id, language_code)
);