--liquibase formatted sql
--changeset Joe Biden:004-create-users
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     uuid UUID UNIQUE DEFAULT gen_random_uuid(),
                                     username VARCHAR(50) UNIQUE NOT NULL,
                                     email VARCHAR(255) UNIQUE NOT NULL,
                                     password VARCHAR(255) NOT NULL,
                                     status_id BIGINT REFERENCES user_statuses(id) DEFAULT 1, -- ACTIVE
                                     deleted BOOLEAN DEFAULT FALSE,
                                     created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                                     updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                                     deleted_at TIMESTAMP WITH TIME ZONE
);
