--liquibase formatted sql
--changeset Joe Biden:005-create-roles
CREATE TABLE IF NOT EXISTS roles (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS role_translations (
                                                 role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                                                 language_code CHAR(2) NOT NULL,
                                                 description VARCHAR(500),
                                                 PRIMARY KEY (role_id, language_code)
);