--liquibase formatted sql
--changeset Joe Biden:006-create-permissions
CREATE TABLE IF NOT EXISTS permissions (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS permission_translations (
                                                       permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
                                                       language_code CHAR(2) NOT NULL,
                                                       description VARCHAR(500),
                                                       PRIMARY KEY (permission_id, language_code)
);

CREATE TABLE IF NOT EXISTS role_permissions (
                                                role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                                                permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
                                                PRIMARY KEY (role_id, permission_id)
);