--liquibase formatted sql
--changeset Joe Biden:007-create-user-profiles
CREATE TABLE IF NOT EXISTS user_profiles (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                                             first_name VARCHAR(50),
                                             last_name VARCHAR(50),
                                             language VARCHAR(10),
                                             birth_date DATE,
                                             gender_id BIGINT REFERENCES genders(id),
                                             avatar_url VARCHAR(255),
                                             region VARCHAR(50),
                                             height NUMERIC(5,2),
                                             weight NUMERIC(5,2),
                                             deleted BOOLEAN DEFAULT FALSE,
                                             created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                                             updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);