--liquibase formatted sql
--changeset Joe Biden:011-create-password-reset-tokens
CREATE TABLE IF NOT EXISTS password_reset_tokens (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                                     token VARCHAR(255) UNIQUE NOT NULL,
                                                     expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                                     used BOOLEAN DEFAULT FALSE,
                                                     created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);