name: Code Style Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  checkstyle:
    uses: New-Fitness/.github/.github/workflows/java-style-check.yml@main
